"""Inertia template tags for Django templates.

Usage:
    {% load inertia %}

    <!DOCTYPE html>
    <html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>My App</title>
        {% vite %}
    </head>
    <body>
        <div id="app" data-page='{{ page }}'></div>
    </body>
    </html>
"""

from django import template
from django.utils.safestring import mark_safe

register = template.Library()


@register.simple_tag
def vite() -> str:
    """
    Generate Vite script and style tags for the Inertia app.

    In development mode, this generates tags that load from the Vite dev server.
    In production mode, this generates tags that load from the built assets
    using the Vite manifest.

    The entry point is configured via CROSS_INERTIA['VITE_ENTRY'] in settings.

    Returns:
        HTML string with script and link tags

    Example:
        {% load inertia %}

        <head>
            {% vite %}
        </head>
    """
    from inertia.django.shortcuts import get_inertia_response

    response = get_inertia_response()
    return mark_safe(response.get_vite_tags())


@register.simple_tag
def inertia_head(head: list[str] | None = None) -> str:
    """
    Render SSR head tags.

    When SSR is enabled, this renders the head tags generated by the SSR server.
    Use this in the <head> section of your template.

    Args:
        head: List of head tag strings from SSR (passed from view context)

    Returns:
        HTML string with head tags

    Example:
        {% load inertia %}

        <head>
            {% vite %}
            {% inertia_head head %}
        </head>
    """
    if head:
        return mark_safe("\n".join(head))
    return ""


@register.simple_tag
def inertia_body(body: str | None = None) -> str:
    """
    Render SSR body content.

    When SSR is enabled, this renders the pre-rendered body content from
    the SSR server. Use this inside your app container div.

    Args:
        body: Body HTML string from SSR (passed from view context)

    Returns:
        HTML string with body content

    Example:
        {% load inertia %}

        <div id="app" data-page='{{ page }}'>
            {% inertia_body body %}
        </div>
    """
    if body:
        return mark_safe(body)
    return ""


@register.inclusion_tag("inertia/app.html", takes_context=True)
def inertia_app(context: dict) -> dict:
    """
    Render the complete Inertia app container.

    This is a convenience tag that renders the app div with data-page
    attribute and optional SSR content.

    Example:
        {% load inertia %}

        <body>
            {% inertia_app %}
        </body>

    Template (inertia/app.html):
        <div id="app" data-page='{{ page }}'>{% inertia_body body %}</div>
    """
    return {
        "page": context.get("page", "{}"),
        "body": context.get("body", ""),
    }
